import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
const product='/products/arc-modular-sofa';
const select=async(page,index,value)=>page.locator(`[data-option-index="${index}"] input[value="${value}"]`).check({force:true});
async function add(page){await page.locator('[data-add-to-cart]').click();await expect(page.locator('#CartDrawer')).toBeVisible();}
async function allImages(page){await page.evaluate(async()=>{for(let y=0;y<document.body.scrollHeight;y+=700){scrollTo(0,y);await new Promise(r=>setTimeout(r,70));}scrollTo(0,0);});await page.waitForTimeout(300);}
test('home has original furniture imagery, linked room products and no console errors',async({page})=>{const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await expect(page.getByRole('heading',{level:1})).toContainText('room to be');await allImages(page);expect(await page.locator('img').evaluateAll(images=>images.filter(i=>!i.complete||!i.naturalWidth).map(i=>i.src))).toEqual([]);expect(errors).toEqual([]);await page.screenshot({path:'evidence/home-desktop.png',fullPage:true});});
test('3D is selectively loaded, responds to material/size and supports dimensions',async({page})=>{const requests=[];page.on('request',r=>requests.push(r.url()));await page.goto(product);expect(requests.some(u=>/configurator\.js|\.glb/.test(u))).toBe(false);await page.locator('[data-view="3d"]').click();await expect(page.locator('[data-viewer]')).toHaveAttribute('data-ready','true',{timeout:45000});await select(page,0,'Generous');await select(page,1,'Bouclé');await select(page,2,'Moss');await expect(page.locator('[data-viewer]')).toHaveAttribute('data-model','Generous');await expect(page.locator('[data-product-price]')).toContainText('4,290');await page.locator('[data-dimensions]').click();await expect(page.locator('[data-dimension-labels]')).toContainText('284 cm');await page.locator('[data-viewer]').focus();await page.keyboard.press('ArrowLeft');await page.locator('[data-viewer-reset]').click();await page.screenshot({path:'evidence/configurator-desktop.png',fullPage:true});await page.locator('[data-view="gallery"]').click();await expect(page.locator('[data-gallery]')).toBeVisible();});
test('rapid model changes cannot replace the final selection with an earlier network response',async({page})=>{await page.goto(product);await page.locator('[data-view="3d"]').click();await expect(page.locator('[data-viewer]')).toHaveAttribute('data-model','Compact',{timeout:45000});await page.route('**/arc-generous.glb',async route=>{await new Promise(r=>setTimeout(r,900));await route.continue();});await select(page,0,'Generous');await select(page,0,'Compact');await page.waitForTimeout(1500);await expect(page.locator('[data-viewer]')).toHaveAttribute('data-model','Compact');});
test('a failed lazy model request leaves the complete gallery and purchase selection usable',async({page})=>{const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*.glb',r=>r.abort());await page.goto(product);await page.locator('[data-view="3d"]').click();await expect(page.locator('[data-gallery-hint]')).toContainText('could not load',{timeout:45000});await expect(page.locator('[data-gallery]')).toBeVisible();await select(page,2,'Clay');await add(page);await expect(page.locator('[data-drawer-body]')).toContainText('Clay');expect(errors).toEqual([]);});
test('exact shared configuration survives navigation and produces the correct cart price',async({page,context})=>{await page.goto(product);await select(page,0,'Generous');await select(page,1,'Bouclé');await select(page,2,'Moss');const url=page.url();expect(new URL(url).searchParams.get('variant')).toBe('71000000000017');const second=await context.newPage();await second.goto(url);await expect(second.locator('[data-variant-select]')).toHaveValue('71000000000017');await add(second);await expect(second.locator('[data-drawer-body]')).toContainText('Generous / Bouclé / Moss');await expect(second.locator('[data-drawer-total]')).toContainText('4,290');await second.reload();await second.locator('[data-cart-open]').click();await expect(second.locator('[data-drawer-total]')).toContainText('4,290');await second.close();});
test('sold-out variants and products cannot be added',async({page})=>{await page.goto(product);await select(page,0,'Chaise');await select(page,1,'Wool');await select(page,2,'Ink');await expect(page.locator('[data-add-to-cart]')).toBeDisabled();await expect(page.locator('[data-variant-notice]')).toContainText('unavailable');const status=await page.evaluate(async()=>{const r=await fetch('/cart/add.js',{method:'POST',body:JSON.stringify({items:[{id:71000000000035,quantity:1}]})});return r.status;});expect(status).toBe(422);await page.goto('/products/halo-pendant');await expect(page.locator('[data-add-to-cart]')).toBeDisabled();});
test('cart supports quantity changes and removal by line-item key',async({page})=>{await page.goto('/products/material-library');await add(page);await page.locator('#CartDrawer [data-cart-step="1"]').click();await expect(page.locator('[data-drawer-total]')).toContainText('30');await page.locator('#CartDrawer [data-cart-remove]').click();await expect(page.locator('[data-drawer-body]')).toContainText('A little space');await expect(page.locator('[data-cart-count]')).toHaveText('(0)');});
test('collection filters, sorting, empty states and search have real results',async({page})=>{await page.goto('/collections/all');await expect(page.locator('[data-collection-grid] [data-product-card]')).toHaveCount(12);await page.locator('#CategoryFilter').selectOption('Tables');await page.locator('#PriceFilter').fill('1300');await page.getByRole('button',{name:'Apply',exact:true}).click();await expect(page.locator('[data-collection-grid] [data-product-card]')).toHaveCount(2);await page.locator('#PriceFilter').fill('1');await page.getByRole('button',{name:'Apply',exact:true}).click();await expect(page.getByRole('heading',{name:'No pieces found.'})).toBeVisible();await page.goto('/search?q=sofa&type=product');await expect(page.locator('.search-page [data-product-card]')).toHaveCount(1);});
test('comparison persists, respects a three-product limit and loads product details',async({page})=>{await page.goto('/collections/all');for(const handle of ['arc-modular-sofa','vale-lounge-chair','monolith-coffee-table','miro-dining-chair']) await page.locator(`[data-compare="${handle}"]`).click();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('forme:compare:v1')).length)).toBe(3);await page.goto('/pages/compare');await expect(page.locator('[data-comparison-content]')).toContainText('Arc modular sofa');await expect(page.locator('[data-comparison-content]')).toContainText('Dimensions');await expect(page.locator('[data-comparison-content]')).toContainText('Travertine',{ignoreCase:true});});
test('fabric samples complete an explicitly simulated order with no payment fields',async({page})=>{await page.goto('/products/material-library');await add(page);await page.locator('#CartDrawer [name="checkout"]').click();await expect(page.getByRole('heading',{name:'A place in your home.'})).toBeVisible();await expect(page.locator('.demo-warning')).toContainText('not Shopify test mode');expect(await page.locator('input[autocomplete="cc-number"]').count()).toBe(0);await page.locator('#DemoConsent').check();await page.getByRole('button',{name:'Complete simulated order'}).click();await expect(page.getByRole('heading',{name:'Thoughtfully chosen.'})).toBeVisible();await expect(page.locator('.preview-order-line').first()).toContainText('The material library');await expect(page.locator('.demo-warning')).toContainText('No payment');await page.screenshot({path:'evidence/simulated-order.png',fullPage:true});await page.reload();await expect(page.getByRole('heading',{name:'Thoughtfully chosen.'})).toBeVisible();});
test('newsletter validates email and clearly reports simulated submission',async({page})=>{await page.goto('/');await page.locator('#NewsletterEmail').fill('reader@example.com');await page.getByRole('button',{name:'Subscribe to the journal'}).click();await expect(page.locator('.preview-form-result')).toContainText('No email was sent');});
test('mobile navigation, product configuration and cart do not overflow',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto('/');await page.getByRole('button',{name:'Open navigation'}).click();await expect(page.locator('#MobileNavigation')).toBeVisible();await page.keyboard.press('Escape');await allImages(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'evidence/home-mobile.png',fullPage:true});await page.goto(product);await select(page,0,'Chaise');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await add(page);await expect(page.locator('#CartDrawer')).toBeVisible();await page.screenshot({path:'evidence/product-mobile.png',fullPage:true});});
test('keyboard users have visible landmarks and no serious axe violations',async({page})=>{for(const route of ['/',product,'/collections/all','/cart','/pages/compare']){await page.goto(route);await page.keyboard.press('Tab');const results=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(results.violations.filter(v=>['critical','serious'].includes(v.impact)),`${route}: ${JSON.stringify(results.violations)}`).toEqual([]);}});
