/** Generates an import worksheet; never writes to a merchant store. */
import fs from 'node:fs/promises';
const products=JSON.parse(await fs.readFile('fixtures/catalog.json','utf8'));
const repository='https://raw.githubusercontent.com/azerish25-ux/FORME-A-luxury-furniture-store-with-an-interactive-3D-product-configurator/main/assets/';
const columns=['Handle','Title','Body (HTML)','Vendor','Type','Tags','Published','Option1 Name','Option1 Value','Option2 Name','Option2 Value','Option3 Name','Option3 Value','Variant SKU','Variant Inventory Tracker','Variant Inventory Qty','Variant Inventory Policy','Variant Fulfillment Service','Variant Price','Variant Requires Shipping','Variant Taxable','Image Src','Image Position','Image Alt Text','Status'];
const quote=value=>'"'+String(value??'').replaceAll('"','""')+'"';
const rows=[];
for(const product of products){for(const [index,variant] of product.variants.entries()){const row={Handle:product.handle,Title:index?'':product.title,'Body (HTML)':index?'':product.description,Vendor:index?'':'FORME',Type:index?'':product.type,Tags:index?'':'FORME-portfolio, '+product.tags.join(', '),Published:'FALSE','Variant SKU':variant.sku,'Variant Inventory Tracker':'shopify','Variant Inventory Qty':variant.inventory_quantity,'Variant Inventory Policy':'deny','Variant Fulfillment Service':'manual','Variant Price':(variant.price/100).toFixed(2),'Variant Requires Shipping':'TRUE','Variant Taxable':'TRUE',Status:'draft'};product.options.forEach((name,i)=>{row[`Option${i+1} Name`]=name;row[`Option${i+1} Value`]=variant.options[i];});if(index===0){row['Image Src']=repository+product.handle+'.webp';row['Image Position']=1;row['Image Alt Text']=product.title+' — original studio render';}rows.push(columns.map(c=>quote(row[c])).join(','));}for(let i=1;i<product.images.length;i++){const row={Handle:product.handle,'Image Src':repository+product.images[i].src.split('/').pop(),'Image Position':i+1,'Image Alt Text':product.images[i].alt};rows.push(columns.map(c=>quote(row[c])).join(','));}}
await fs.mkdir('docs/import',{recursive:true});await fs.writeFile('docs/import/forme-products.csv',columns.map(quote).join(',')+'\n'+rows.join('\n')+'\n');
await fs.writeFile('docs/import/metafield-values.json',JSON.stringify(products.map(p=>({handle:p.handle,templateSuffix:p.handle==='arc-modular-sofa'?'arc':'',values:Object.fromEntries(Object.entries(p.metafields.custom).map(([k,v])=>['custom.'+k,v.value]))})),null,2)+'\n');
console.log('Draft-product import CSV and metafield worksheet generated. Review them before importing. Fixture IDs are deliberately excluded.');
