/** Generate Shopify-safe Liquid records from the same specification Blender and JS consume. */
import fs from 'node:fs/promises';
const spec = JSON.parse(await fs.readFile('tools/arc-spec.json', 'utf8'));
const quote = JSON.stringify;
const asset = filename => `{{ '${filename}' | asset_url | json }}`;
const dimensions = Object.fromEntries(Object.entries(spec.sizes).map(([name, value]) => [name, value.dimensions]));
const config = `{"arc":{{ is_arc | json }},"enabled":{{ allow_3d | json }},"revision":${spec.version},"assetBase":${asset('arc-asset-manifest.json')},"models":{${Object.entries(spec.sizes).map(([name, value]) => `${quote(name)}:${asset(value.model)}`).join(',')}},"dimensions":${quote(dimensions)},"colours":${quote(Object.fromEntries(Object.entries(spec.colours).map(([name, value]) => [name, value.hex])))},"fabrics":${quote(spec.fabrics)},"delivery":{{ product.metafields.custom.delivery.value | default: section.settings.delivery_text | json }}}`;
await fs.writeFile('snippets/arc-config.liquid', `{% comment %}Generated by scripts/generate-arc.mjs. Edit tools/arc-spec.json.{% endcomment %}\n${config}\n`);
let poster = `{%- comment -%}Generated from tools/arc-spec.json; unknown options use the merchant gallery.{%- endcomment -%}\n`;
for (const [index, name] of spec.optionNames.entries()) {
  poster += `{%- assign arc_value_${index} = '' -%}{%- for option in product.options_with_values -%}{%- if option.name == '${name}' -%}{%- assign arc_value_${index} = variant.options[forloop.index0] -%}{%- endif -%}{%- endfor -%}\n`;
  const group = [spec.sizes, spec.fabrics, spec.colours][index];
  poster += `{%- assign arc_slug_${index} = '' -%}{%- case arc_value_${index} -%}${Object.entries(group).map(([name, value]) => `{%- when '${name}' -%}{%- assign arc_slug_${index} = '${value.id}' -%}`).join('')}{%- endcase -%}\n`;
}
poster += `{%- if arc_slug_0 != '' and arc_slug_1 != '' and arc_slug_2 != '' -%}{%- assign arc_filename = '${spec.poster.prefix}' | append: arc_slug_0 | append: '-' | append: arc_slug_1 | append: '-' | append: arc_slug_2 | append: '.webp' -%}{{- arc_filename | asset_url -}}{%- endif -%}\n`;
await fs.writeFile('snippets/arc-poster.liquid', poster);
const measurement = `{%- comment -%}Generated from the Arc design specification.{%- endcomment -%}{%- for option in product.options_with_values -%}{%- if option.name == 'Size' -%}{%- assign size = variant.options[forloop.index0] -%}{%- case size -%}${Object.entries(spec.sizes).map(([name,value])=>`{%- when '${name}' -%}${value.dimensions.join(' × ')} cm`).join('')}{%- endcase -%}{%- endif -%}{%- endfor -%}`;
await fs.writeFile('snippets/arc-measurements.liquid', measurement + '\n');


// Upgrade only the fictional preview catalogue. Shopify prices/IDs are never generated here.
const catalog = JSON.parse(await fs.readFile('fixtures/catalog.json', 'utf8'));
const arc = (Array.isArray(catalog) ? catalog : catalog.products).find(p => p.handle === spec.productHandle);
if (!arc) throw new Error('Arc preview record missing');
for (const variant of arc.variants) {
  const values = spec.optionNames.map(name => variant.options[arc.options.indexOf(name)]);
  const records = [spec.sizes[values[0]], spec.fabrics[values[1]], spec.colours[values[2]]];
  if (records.some(record => !record)) throw new Error(`Unsupported fixture variant ${variant.id}`);
  variant.featured_image = { id: Number(variant.id), src: `/assets/${spec.poster.prefix}${records.map(record => record.id).join('-')}.webp`, width: spec.poster.width, height: spec.poster.height, alt: `Arc · ${variant.title}` };
}
const first = arc.variants[0].featured_image;
arc.featured_image = first;
arc.images = [first, ...spec.gallery.map((image, index) => ({ id: first.id + 100 + index, src: `/assets/${image.file}`, width: spec.poster.width, height: spec.poster.height, alt: image.caption }))];
arc.media = arc.images.map(image => ({ ...image, media_type: 'image', preview_image: image }));
await fs.writeFile('fixtures/catalog.json', JSON.stringify(catalog, null, 2) + '\n');
console.log(`Arc v${spec.version}: generated Liquid contract and ${arc.variants.length} selected-media mappings.`);
